# render.yml
services:
  - type: web # ЁЯСИ рдЗрд╕реЗ 'web' рдкрд░ рд╕реЗрдЯ рдХрд░реЗрдВ
    name: telegram-filter-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT bot:web_app"
    healthCheckPath: /
    envVars:
      - key: API_ID
        value: "123456" # рдЕрдкрдиреА API ID рдпрд╣рд╛рдБ рдбрд╛рд▓реЗрдВ
      - key: API_HASH
        value: "eb06d4abfb49dc3eeb1aeb98ae0f581e" # рдЕрдкрдирд╛ API HASH рдпрд╣рд╛рдБ рдбрд╛рд▓реЗрдВ
      - key: BOT_TOKEN
        value: "50a04ab22e0b3552dd351028a6d1a1c4" # рдЕрдкрдирд╛ BOT TOKEN рдпрд╣рд╛рдБ рдбрд╛рд▓реЗрдВ
      - key: DB_URI
        value: "mongodb://..." # рдЕрдкрдирд╛ MongoDB URI рдпрд╣рд╛рдБ рдбрд╛рд▓реЗрдВ
      - key: ADMINS
        value: "123456789" # рдЕрдкрдиреА рдПрдбрдорд┐рди ID рдпрд╣рд╛рдБ рдбрд╛рд▓реЗрдВ
      - key: LOG_CHANNEL
        value: "-100xxxxxxx"
      - key: PYTHON_VERSION
        value: 3.11.5
        
